name: Extract DT

on: [push]

env:
  DUMP: https://git.rip/dumps/redmi/galahad.git
  BRAND: xiaomi
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'

       - name: Initializing environment
         run: |
              cd /
              sudo mkdir work
              sudo chmod -R 0777 work
              cd work
              
       - name: Clone scripts
         run: |
              cd /work
              sudo git clone https://github.com/ShivamKumarJha/android_tools .
              sudo apt-get install -y python-pip python3-pip python
              sed -i "s|pip3|pip|g" setup.sh
              sudo ./setup.sh
       
       - name: Clone dump
         run: |
              cd /work
              git clone --depth=1 -j8 --single-branch $DUMP dump
              
       - name: Generate DT
         run: |
              cd /work
              sudo ./tools/dummy_dt.sh dump
       
       - name: Upload tard DT
         run: |
              cd /work
              sudo zip -r $BRAND.zip $BRAND
              touch link.txt
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet $BRAND.zip | grep Download >> link.txt       
              
       - name: Get DL link
         run: cat /work/link.txt
              
